### ISSUE TITLE
Repo name/ plugin name

### ISSUE THREAD

**Issue by martinklepsch** [squint-cljs/vite-plugin-squint#1]
Hey! 

just wanted to share [these conventions](https://vitejs.dev/guide/api-plugin#conventions) before we make a first release to NPM, I think `vite-plugin-squint` would adhere to their conventions. 

I think technically this might also be a rollup plugin (vite is a superset of rollup in terms of their plugin API) but I don't have a strong opinion on that. Will explore the differences a bit more and report back.

**Comment by borkdude** [comment]
repo renamed
