### ISSUE TITLE
Add a tiny React example

### ISSUE THREAD

**Issue by martinklepsch** [squint-cljs/vite-plugin-squint#4]
It would be great to have a small example with React usage.

- [ ] Use [@vitejs/plugin-react](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react)
- [ ] Write a small react app that demonstrates local state persisting over refreshes

**Comment by brandonstubbs** [comment]
I added a react demo #7 

The HMR does not work, so we will need to solve that
